### PR TITLE
s

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by dejuknow** [comment]
Merged. Thanks.

**Comment by shinnlok** [comment]
fyi I noticed I missed a line:

<property environment="env" /> should probably go up too

**Comment by dejuknow** [comment]
What should go up? <property environment="env" />?

**Comment by dejuknow** [comment]
ah ... encoding issues. property environment="env"?

**Comment by shinnlok** [comment]
oh yup.

**Pull request closed without merging**
